import percent

from datetime import datetime, date

DATETIME_STRING_FORMAT = "%Y-%m-%d"

def user_overview(tasks, logged_in_user, user_list):
    time_generated = str(datetime.now())
    time_generated = time_generated[:19:]
    
    total_tasks = len(tasks)
    total_users = len(user_list)

    report_list = []
    
    report_overview = f'''Task Overview

Generated by {logged_in_user}

Report generated: {time_generated}

-------------------------------------------------------    

Total number of tasks: \t\t\t\t\t\t {total_tasks}

Total number of users: \t\t\t\t\t\t {total_users}

-------------------------------------------------------'''
    report_list.append(report_overview)
    for u in user_list:
        user_task_total = 0
        user_completed_total = 0
        user_incomplete_total = 0
        user_overdue_total = 0
        for t in tasks:
            if t['username'] == u:
                user_task_total += 1
            if t['username'] == u and t['completed'] == True:
                user_completed_total += 1
            if t['username'] == u and t['completed'] == False:
                user_incomplete_total += 1
            due_date = str(t["due_date"])
            due_date = due_date[:10:]
            today_date = str(date.today())
            if t['username'] == u and t['completed'] == False and due_date < today_date:
                user_overdue_total += 1
        
        # use percent module to calculate percentages
            user_percent_assigned = percent.percentage_of(user_task_total, total_tasks)
            user_percent_completed = percent.percentage_of(user_completed_total, user_task_total)
            user_percent_incomplete = percent.percentage_of(user_incomplete_total, user_task_total)
            user_percent_overdue = percent.percentage_of(user_overdue_total, user_task_total)
        
        user_report = f'''

User: {u}

Number of assigned tasks: \t\t\t\t\t {user_task_total}
Number of completed tasks: \t\t\t\t\t {user_completed_total}
Number of incomplete tasks: \t\t\t\t {user_incomplete_total}
Number of overdue tasks: \t\t\t\t\t {user_overdue_total}

Percentage of tasks assigned to user: \t\t {user_percent_assigned}%
Percentage of assigned completed tasks: \t {user_percent_completed}%
Percentage of assigned incomplete tasks: \t {user_percent_incomplete}%
Percentage of assigned tasks overdue: \t\t {user_percent_overdue}%

-------------------------------------------------------'''
        report_list.append(user_report)


    with open("user_overview.txt", 'w') as f:
        for entry in report_list:
            f.write(entry)
            
    print("Reports generated - use Display Statistics from the main menu to view data from reports")